apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-controller
  namespace: safesoundarena
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-controller
  template:
    metadata:
      labels:
        app: mcp-controller
    spec:
      containers:
      - name: mcp-controller
        image: safesoundarena/mcp-controller:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_PATH
          value: "/etc/mcp/config.yaml"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: mcp-config
          mountPath: /etc/mcp
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: mcp-config
        configMap:
          name: mcp-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-controller-service
  namespace: safesoundarena
spec:
  selector:
    app: mcp-controller
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 