apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-game-config
  namespace: safesoundarena
data:
  game-config.yaml: |
    game_services:
      matchmaking:
        algorithm: "elo-based"
        queue_timeout: 60
        min_players: 2
        max_players: 100
        ranking_threshold: 200
        
      game_rooms:
        instance_types:
          - name: "small"
            max_players: 10
            resources:
              cpu: "500m"
              memory: "1Gi"
          - name: "medium"
            max_players: 50
            resources:
              cpu: "1000m"
              memory: "2Gi"
          - name: "large"
            max_players: 100
            resources:
              cpu: "2000m"
              memory: "4Gi"
              
      game_state:
        sync_interval: 100
        snapshot_interval: 300
        history_retention: 3600
        redis_cache: true
        
      physics_engine:
        tick_rate: 60
        collision_precision: "high"
        world_bounds:
          x: [-1000, 1000]
          y: [-1000, 1000]
          z: [-1000, 1000]
          
      rewards:
        xp_multiplier: 1.0
        token_rewards:
          win: 100
          participation: 10
          achievement: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
  namespace: safesoundarena
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: game-server
        image: safesoundarena/game-server:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 7777
          name: game
        - containerPort: 7778
          name: metrics
        env:
        - name: GAME_CONFIG
          value: "/etc/game/config.yaml"
        volumeMounts:
        - name: game-config
          mountPath: /etc/game
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: game-config
        configMap:
          name: mcp-game-config
---
apiVersion: v1
kind: Service
metadata:
  name: game-server
  namespace: safesoundarena
spec:
  selector:
    app: game-server
  ports:
  - name: game
    port: 7777
    targetPort: game
  - name: metrics
    port: 7778
    targetPort: metrics
  type: LoadBalancer 