[build]
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_PI_SANDBOX = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
