apiVersion: v1
kind: Namespace
metadata:
  name: safesoundarena-staging
  labels:
    environment: staging
    app: safesoundarena
---
apiVersion: v1
kind: Namespace
metadata:
  name: safesoundarena-prod
  labels:
    environment: production
    app: safesoundarena
