// Commonly used UI strings and pull messages for your app
export const COMMON_STRINGS = {
  welcome: "Welcome to SafeSoundArena!",
  loading: "Loading...",
  error: "Something went wrong. Please try again.",
  retry: "Retry",
  submit: "Submit",
  cancel: "Cancel",
  confirm: "Confirm",
  next: "Next",
  previous: "Previous",
  finish: "Finish",
  yes: "Yes",
  no: "No",
  ok: "OK",
  close: "Close",
  search: "Search",
  save: "Save",
  delete: "Delete",
  edit: "Edit",
  copy: "Copy",
  paste: "Paste",
  pull_to_refresh: "Pull to refresh",
  release_to_refresh: "Release to refresh",
  refreshing: "Refreshing...",
  no_results: "No results found.",
  empty_state: "Nothing here yet.",
  sign_in: "Sign in",
  sign_out: "Sign out",
  profile: "Profile",
  settings: "Settings",
  notifications: "Notifications",
  help: "Help",
  about: "About",
  contact: "Contact",
  privacy_policy: "Privacy Policy",
  terms_of_service: "Terms of Service",
};
