const BASE_EMOJIS = {
  QUEST_CATEGORIES: {
    EXPLORATION: '🗺️',
    COMBAT: '⚔️',
    CRAFTING: '⚒️',
    SOCIAL: '🤝',
    TRADING: '💱',
    LEARNING: '📚',
    BUILDING: '🏗️',
    FARMING: '🌾',
    MINING: '⛏️',
    MAGIC: '✨',
  },
  
  DIFFICULTY: {
    NOVICE: '🌱',
    EASY: '🔰',
    MEDIUM: '🌟',
    HARD: '🔥',
    EXPERT: '💫',
    LEGENDARY: '👑',
  },

  STATUS: {
    ONLINE: '🟢',
    AWAY: '🌙',
    BUSY: '⚡',
    GAMING: '🎮',
    EXPLORING: '🔍',
    TRADING: '💰',
    CRAFTING: '🛠️',
    BATTLING: '⚔️',
    MEDITATING: '🧘',
    STREAMING: '🎥',
  },

  ACHIEVEMENTS: {
    COMMON: '🥉',
    RARE: '🥈',
    EPIC: '🥇',
    LEGENDARY: '👑',
    MYTHIC: '🌟',
    SECRET: '🎭',
    SEASONAL: '🎋',
    COMMUNITY: '🤝',
    CHALLENGE: '🏆',
    MASTERY: '⭐',
  },

  EVENTS: {
    TOURNAMENT: '🏟️',
    FESTIVAL: '🎪',
    CHALLENGE: '🎯',
    RAID: '⚔️',
    AUCTION: '🏪',
    CARNIVAL: '🎡',
    EXPEDITION: '🗺️',
    CONTEST: '🏆',
    PARTY: '🎉',
    CEREMONY: '🎭',
  },

  BLOCKCHAIN: {
    REWARD: '🎁',
    TRANSFER: '💸',
    STAKE: '🔒',
    MINE: '⛏️',
    VOTE: '🗳️',
    TRADE: '💱',
    BOND: '🤝',
    YIELD: '🌾',
    BURN: '🔥',
    MINT: '⚡',
  },

  REACTIONS: {
    LIKE: '👍',
    LOVE: '❤️',
    LAUGH: '😄',
    WOW: '😲',
    SAD: '😢',
    ANGRY: '😠',
    SUPPORT: '🤝',
    CELEBRATE: '🎉',
    THINK: '🤔',
    CURIOUS: '👀',
  },

  WEATHER: {
    SUNNY: '☀️',
    RAINY: '🌧️',
    STORMY: '⛈️',
    SNOWY: '🌨️',
    CLOUDY: '☁️',
    WINDY: '💨',
    FOG: '🌫️',
    RAINBOW: '🌈',
    NIGHT: '🌙',
    SUNRISE: '🌅',
  },

  ELEMENTS: {
    FIRE: '🔥',
    WATER: '💧',
    EARTH: '🌍',
    AIR: '💨',
    LIGHT: '✨',
    DARK: '🌑',
    NATURE: '🌿',
    ELECTRIC: '⚡',
    ICE: '❄️',
    COSMIC: '🌌',
  },

  UI: {
    SETTINGS: '⚙️',
    SEARCH: '🔍',
    MENU: '📋',
    CLOSE: '❌',
    ADD: '➕',
    REMOVE: '➖',
    EDIT: '✏️',
    DELETE: '🗑️',
    SAVE: '💾',
    REFRESH: '🔄',
    LINK: '🔗',
    LOCK: '🔒',
    UNLOCK: '🔓',
    WARNING: '⚠️',
    ERROR: '❌',
    SUCCESS: '✅',
    INFO: 'ℹ️',
    HELP: '❓',
    TIME: '⏰',
    CALENDAR: '📅',
    BUY: '🛒',
  },
} as const;

export const EMOJIS = {
  ...BASE_EMOJIS,
  // Top-level aliases for convenience and legacy usage
  TIME: BASE_EMOJIS.UI.TIME,
  LINK: BASE_EMOJIS.UI.LINK,
  MENU: BASE_EMOJIS.UI.MENU,
  SETTINGS: BASE_EMOJIS.UI.SETTINGS,
  WARNING: BASE_EMOJIS.UI.WARNING,
  ERROR: BASE_EMOJIS.UI.ERROR,
  SUCCESS: BASE_EMOJIS.UI.SUCCESS,
  INFO: BASE_EMOJIS.UI.INFO,
  HELP: BASE_EMOJIS.UI.HELP,
  BUY: BASE_EMOJIS.UI.BUY,
  CALENDAR: BASE_EMOJIS.UI.CALENDAR,
} as const;
