export const EMOJIS = {
  QUEST_CATEGORIES: {
    EXPLORATION: '🗺️',
    COMBAT: '⚔️',
    CRAFTING: '⚒️',
    SOCIAL: '🤝',
    TRADING: '💱',
    LEARNING: '📚',
    BUILDING: '🏗️',
    FARMING: '🌾',
    MINING: '⛏️',
    MAGIC: '✨',
  },

  DIFFICULTY: {
    NOVICE: '🌱',
    EASY: '🔰',
    MEDIUM: '🌟',
    HARD: '🔥',
    EXPERT: '💫',
    LEGENDARY: '👑',
  },

  STATUS: {
    ONLINE: '🟢',
    AWAY: '🌙',
    BUSY: '⚡',
    GAMING: '🎮',
    EXPLORING: '🔍',
    TRADING: '💰',
    CRAFTING: '🛠️',
    BATTLING: '⚔️',
    MEDITATING: '🧘',
    STREAMING: '🎥',
  },

  ACHIEVEMENTS: {
    COMMON: '🥉',
    RARE: '🥈',
    EPIC: '🥇',
    LEGENDARY: '👑',
    MYTHIC: '🌟',
    SECRET: '🎭',
    SEASONAL: '🎋',
    COMMUNITY: '🤝',
    CHALLENGE: '🏆',
    MASTERY: '⭐',
  },

  EVENTS: {
    TOURNAMENT: '🏟️',
    FESTIVAL: '🎪',
    CHALLENGE: '🎯',
    RAID: '⚔️',
    AUCTION: '🏪',
    CARNIVAL: '🎡',
    EXPEDITION: '🗺️',
    CONTEST: '🏆',
    PARTY: '🎉',
    CEREMONY: '🎭',
  },

  BLOCKCHAIN: {
    REWARD: '🎁',
    TRANSFER: '💸',
    STAKE: '🔒',
    MINE: '⛏️',
    VOTE: '🗳️',
    TRADE: '💱',
    BOND: '🤝',
    YIELD: '🌾',
    BURN: '🔥',
    MINT: '⚡',
  },

  REACTIONS: {
    LIKE: '👍',
    LOVE: '❤️',
    LAUGH: '😄',
    WOW: '😲',
    SAD: '😢',
    ANGRY: '😠',
    SUPPORT: '🤝',
    CELEBRATE: '🎉',
    THINK: '🤔',
    CURIOUS: '👀',
  },

  WEATHER: {
    SUNNY: '☀️',
    RAINY: '🌧️',
    STORMY: '⛈️',
    SNOWY: '🌨️',
    CLOUDY: '☁️',
    WINDY: '💨',
    FOG: '🌫️',
    RAINBOW: '🌈',
    NIGHT: '🌙',
    SUNRISE: '🌅',
  },

  ELEMENTS: {
    FIRE: '🔥',
    WATER: '💧',
    EARTH: '🌍',
    AIR: '💨',
    LIGHT: '✨',
    DARK: '🌑',
    NATURE: '🌿',
    ELECTRIC: '⚡',
    ICE: '❄️',
    COSMIC: '🌌',
  },

  UI: {
    SETTINGS: '⚙️',
    SEARCH: '🔍',
    MENU: '📋',
    CLOSE: '❌',
    ADD: '➕',
    REMOVE: '➖',
    EDIT: '✏️',
    DELETE: '🗑️',
    SAVE: '💾',
    REFRESH: '🔄',
    LINK: '🔗',
    LOCK: '🔒',
    UNLOCK: '🔓',
    WARNING: '⚠️',
    ERROR: '❌',
    SUCCESS: '✅',
    INFO: 'ℹ️',
    HELP: '❓',
    TIME: '⏰',
    CALENDAR: '📅',
    BUY: '🛒',
  },
} as const;
