global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'api-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-server:4000']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: 'game-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['game-service:7777']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'game_.*'
        action: keep

  - job_name: 'blockchain-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['blockchain-service:8545']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'eth_.*'
        action: keep

  - job_name: 'matchmaking-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['matchmaking-service:6000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-exporter:9116']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: 'http://victoria-metrics:8428/api/v1/write'
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 1000
      batch_send_deadline: 5s

remote_read:
  - url: 'http://victoria-metrics:8428/api/v1/read'
    read_recent: true 