# GitHub Actions workflow for automated tests & code coverage
# Place this file at .github/workflows/ci.yml in your repo

name: Frontend CI

on:
  push:
<<<<<<< HEAD
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master
  workflow_dispatch: # Enable manual triggering of workflow
    inputs:
      reason:
        description: 'Reason for triggering the workflow'
        required: false
=======
    branches: [main, master]
  pull_request:
    branches: [main, master]
>>>>>>> 9841034 (Initial full project commit: user/admin dashboards, tasks, notifications, MongoDB, and statistics features)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests with coverage
        run: |
          cd frontend
          npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/lcov.info
          flags: unittests
          name: codecov-frontend
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
<<<<<<< HEAD

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Display Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workflow triggered manually: ${{ github.event.inputs.reason }}"
=======
>>>>>>> 9841034 (Initial full project commit: user/admin dashboards, tasks, notifications, MongoDB, and statistics features)
