# .github/workflows/ci.yml
# GitHub Actions CI: Run tests on every push & PR
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: npm install
      - name: Build backend (if applicable)
        run: |
          if [ -f server.js ]; then npm run build || echo "No build script"; fi
      - name: Test backend (if applicable)
        run: |
          if [ -f server.js ]; then npm test || echo "No tests"; fi
      - name: Install frontend dependencies
        run: |
          cd frontend && npm install
      - name: Build frontend
        run: |
          cd frontend && npm run build
      - name: Test frontend
        run: |
          cd frontend && npm run test || echo "No frontend tests"
